services:
  prme:
    build:
      args:
        VERSION_SHA: docker-development
    ports:
      - "8080:8080"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8080
      - DISK_CACHE_ENABLED=true
      - DISK_CACHE_BASE_PATH=/cache_data
      - GH_APP_ID=0
      - GH_INSTALLATION_ID=0
    volumes:
      - ./data:/cache_data
