#!/bin/bash -euo pipefail

cd "$(dirname ${BASH_SOURCE})"

if [ $# -eq 0 ]; then
    trap 'trap " " SIGTERM; kill 0; wait' SIGINT SIGTERM
    ./dev go &
    ./dev tailwind &
    wait
    exit 0
fi

case "$1" in
  go)
    exec env $(cat .env | xargs) go run github.com/cespare/reflex -d none -c reflex.conf
    ;;
  tailwind)
    exec tailwindcss -i cmd/veun/static/input.css -o cmd/veun/static/dev-styles.css --watch
    ;;
  *)
    echo "??? $1 ???"
    exit 1
    ;;
esac
