version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
    - $PORT:$PORT
    volumes:
    - .:/go/src/app  # for dev
    - cache-content:/tmp/data/cache:rw
    environment:
    - PORT=${PORT}
    - DISK_CACHE_ENABLED=true
    - DISK_CACHE_BASE_PATH=/tmp/data/cache
    - GH_APP_ID=${GH_APP_ID}
    - GH_INSTALLATION_ID=${GH_INSTALLATION_ID}
    - GH_PK_FILE=${GH_PK_FILE}
volumes:
  cache-content:
