#!/bin/bash
set -euo pipefail

YARN_VERSION=1.22.19

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR="$SCRIPT_DIR/../"
cd "$PROJECT_DIR"

# make sure we have the right version of YARN installed
npm install -g "yarn@$YARN_VERSION"

# get the project prequisites running good
pushd frontend
yarn install
popd
