name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cashapp/activate-hermit@v1
    - name: test
      run: |-
        cd server
        go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cashapp/activate-hermit@v1
    - name: shellcheck
      run: |-
        shellcheck bin/prmectl
    - name: lint-golang
      run: |-
        cd server
        golangci-lint run
    - name: lint-vue
      run: |-
        cd frontend
        yarn 
        yarn lint

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cashapp/activate-hermit@v1
    - name: generate
      run: |-
        cd frontend
        yarn
        yarn generate
