name: Pull Request

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cashapp/activate-hermit@v1
    - name: build-server
      run: go build ./cmd/veun
    - name: test
      run: go test ./...
    - name: lint
      run: golangci-lint run

  # prmectl: just make sure that it's going to be ok.
  prmectl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cashapp/activate-hermit@v1
    - name: shellcheck
      run:  shellcheck bin/prmectl
