name: Pull Request

on:
  push:
    branches: 
    - main 
  pull_request:
    branches: 
    - main

jobs:

  # server: 
  # can we run the server, is the API alright?
  #
  # Priority is to fail fast, so first can we compile and build 
  # the server binary, then tests, and linting.
  server:
    defaults:
      working-directory: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cashapp/activate-hermit@v1
    - name: build-server
      run: go build ./cmd/server
    - name: test
      run: go test ./...
    - name: lint
      run: golangci-lint run

  # frontend: describes the steps we take to 
  # ensure that the nuxt application is buildable.
  # 
  # The priority here is to fail fast on critical things.
  # 1. We can actually build the application
  # 2. It typechecks & lints
  frontend:
    runs-on: ubuntu-latest
    defaults:
      working-directory: frontend
    steps:
    - uses: actions/checkout@v3
    - uses: cashapp/activate-hermit@v1
    - name: yarn
      run: yarn
    - name: generate
      run: yarn generate
    - name: lint
      run: yarn lint
    - name: typecheck
      run: yarn nuxi typecheck
  
  # prmectl: just make sure that it's going to be ok.
  prmectl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cashapp/activate-hermit@v1
    - name: shellcheck bin/prmectl
      run:  shellcheck bin/prmectl
